name: learn_flutter_webrtc
description: "A LiveKit WebRTC implementation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # LiveKit WebRTC
  livekit_client: ^2.4.1
  webrtc_interface: ^1.1.2
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Utilities
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  uuid: ^4.3.3
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0 
  
  # UI Components
  permission_handler: ^11.3.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation Tools
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets: 
    - .env
